default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('MAX_THREADS') { 5 } %>
#  username: <%= ENV.fetch('DATABASE_USER') %>
#  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>

development:
  <<: *default
  database: <%= ENV.fetch('DEV_DATABASE_NAME') %>

test:
  <<: *default
  database: <%= ENV.fetch('TEST_DATABASE_NAME') %>

production:
  <<: *default
  database: <%= ENV.fetch('PROD_DATABASE_NAME') %>